export const pathLocations = {
  login: "/login",
  signup: "/sign-up",
  home: "/",
  aboutUs: "/about-us",
  blogs: "/blogs",
  furnitureGallery: "/furniture-gallery",
  faq: "/faq",
  privacyPolicy: "/privacy-policy",
  termsAndCondition: "/terms-and-conditions",
  contactUs: "/contact-us",
  virtualStaging: "/services/virtual-staging",
  virtualRenovation: "/services/virtual-renovation",
  virtualTwilight: "/services/virtual-twilights",
  commercialVirtualStaging: "/services/commercial-virtual-staging",
  commercialVirtualRenovation: "/services/commercial-virtual-renovation",
  placeOrder: "/place-order",
  premadeGallery: "/residential-premade-gallery",
  profile: "/profile",
  order: "/order",
  curatedCollection: "/curated-collection",
  styles: "/styles",
};
